import Head from "next/head";

export default function Header() {
    return (
        <Head>
            <title>DMIT2015 - Course Project</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
    )
}