// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace CShap.RestApi.Entities;

public partial class bill
{
    public int billid { get; set; }

    public string payeename { get; set; }

    public double paymentdue { get; set; }

    public bool paid { get; set; }

    public DateTime createdat { get; set; }

    public DateTime updatedat { get; set; }

    public string createdby { get; set; }
}