// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using CShap.RestApi.Entities;
using Microsoft.EntityFrameworkCore;

namespace CShap.RestApi.DAL;

public partial class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public virtual DbSet<bill> bills { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<bill>(entity =>
        {
            entity.HasKey(e => e.billid).HasName("bills_pkey");

            entity.Property(e => e.createdat).HasDefaultValueSql("now()");
            entity.Property(e => e.createdby).HasMaxLength(50);
            entity.Property(e => e.payeename)
                .IsRequired()
                .HasMaxLength(20);
            entity.Property(e => e.updatedat).HasDefaultValueSql("now()");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}